config/routes.rb
Rails.application.routes.draw do

  resources :categories

  resources :jobs

  resources :job_applications

  root :to => 'demo#landing'

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, :has_one => :job_seeker
  resources :admin_users

  resources :login

  resources :user

  resources :jobs

  resources :demo

  get "error"=>"demo#error",:as => "error"
  get "contact"=>"demo#contact", :as => "contact"
  resources :employers

  resources :job_seeker
  post "/status" =>  "job_applications#status"

  resources :job_applications
  get "applicationsbyjobid" => "jobapplications#applicationsbyjobid", :as =>"applicationsbyjobid"

  get "edit_status" =>"jobapplications#editstatus", :as =>"edit_applicationstatus"
  get "create_job" =>"jobs#new", :as =>"create_job"

match ':controller(/:action(/:id))', :via => [:get,:post]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  validates  :admin_name, :presence => true
  validates :email, :presence => true,:uniqueness => true
  validates :password, :presence => true

  attr_accessible :email,:password,:admin_name,:user_id
	has_many :categories
	has_many :employers, :through => :categories



end

app/models/category.rb
class Category < ActiveRecord::Base
	
	belongs_to :creator, :class_name =>"AdminUser", :foreign_key => "admin_user_id"
	has_and_belongs_to_many :employers
	belongs_to :jobs
  attr_accessible :name

end

app/models/employer.rb
class Employer < ActiveRecord::Base
	belongs_to :admin, :class_name =>"AdminUser", :foreign_key => "admin_user_id"
	has_many :tags
	has_many :jobs

  attr_accessible :company_name

  validates :admin_id, :presence => true
 
end

app/models/job.rb
class Job < ActiveRecord::Base

  belongs_to :employer
  belongs_to :category

  has_many :job_applications
  has_many :tags, :class_name => 'Job'
  accepts_nested_attributes_for :tags, :allow_destroy => true
  attr_accessible :title,:description,:application_deadline, :category_id, :employer
  def self.search(search)
    if search
      # paginate :per_page => 5, :page => 1,
      # :conditions => ["title LIKE '%?' ",search,search], :order => 'title'
      find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
    else
      all
    end
  end

end

app/models/job_application.rb
class JobApplication < ActiveRecord::Base

  belongs_to :jobs
  belongs_to :job_seekers
  validates :job_id,  presence: true
  validates :job_seeker_id, presence: true
  validates :status, :presence => true

  attr_accessible :cover_letter,:application_deadline

# <!-- Assigning Integer Values to various Job Application states - Using the standard Naming convention for Constants -->
  STATE_PENDING = 0
  STATE_FUTUREINTERVIEW = 1
  STATE_NOTAFIT = 2

  STATE_PENDING_STRING = 'Pending'
  STATE_FUTUREINTERVIEW_STRING = 'Future interview'
  STATE_NOTAFIT_STRING = 'Not a fit'

  def getApplicationState
    case self.status
      when STATE_FUTUREINTERVIEW
        return STATE_FUTUREINTERVIEW_STRING
      when STATE_PENDING
        return STATE_PENDING_STRING
      when STATE_NOTAFIT
        return STATE_NOTAFIT_STRING
      else
        return 'Pending review'
    end
  end

end

app/models/job_seeker.rb
class JobSeeker < ActiveRecord::Base

has_many :job_applications
  validates :first_name, :presence => true,:format=> { with: /\A[a-zA-Z\s]*\z/, on: :create }
  validates :last_name, :presence => true,:format=> { with: /\A[a-zA-Z\s]*\z/, on: :create }
  #validates :email, :presence => true,:format=> { with: /\A([^@\s]+)@((?:[a-zA-Z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  #validates :password, :presence => true, :length => {minimum: 8}
  validates :resume, :presence => true

	scope :sorted, lambda{order("job_seekers.name_first ASC")}
	scope :newest_first, lambda{order("job_seekers.created_at DESC")}
	scope :search, lambda{|query|
		where(["name_first LIKE ?","%#{query}%"])
}

end

app/models/job_tag.rb
class JobTag < ActiveRecord::Base
	belongs_to :creator, :class_name => "Job", :foreign_key => "job_id"
	belongs_to :creator, :class_name => "Tag", :foreign_key => "tag_id"
  attr_accessible :tag_id,:job_id
  #attr_reader :tag_id,:job_id
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	belongs_to :creator, :class_name => "Employer", :foreign_key => "employer_id"
  attr_accessible :tag_value
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
 # has_one :job_seeker
  attr_accessible :email,:first_name,:last_name, :password, :password_confirmation, :remember_me, :job_seeker_attributes
 # accepts_nested_attributes_for :job_seeker

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  skip_before_action :authenticate_user!
  layout false
  def index

  end

  def hello
    # render('index')
    @array = [1,2,3,5,6]
    @id = params['id']
    @page_no = params['page']
    @random = params['rand']
  end

  def other_hello
    redirect_to(:controller => 'demo', :action => 'index' )
  end

  def google
    redirect_to("http://www.google.co.in")
  end

end

app/controllers/job_seekers_controller.rb
class JobSeekersController < ApplicationController
  before_action :set_job_seeker, only: [:show, :edit, :update, :destroy]

  # GET /job_seekers
  # GET /job_seekers.json
  def index
    @job_seekers = JobSeeker.all
  end

  # GET /job_seekers/1
  # GET /job_seekers/1.json
  def show
  end

  # GET /job_seekers/new
  def new
    @job_seeker = JobSeeker.new
  end

  # GET /job_seekers/1/edit
  def edit
  end

  # POST /job_seekers
  # POST /job_seekers.json
  def create
    @job_seeker = JobSeeker.new(job_seeker_params)
    respond_to do |format|
      if @job_seeker.save
        format.html { redirect_to @job_seeker, notice: 'Job seeker was successfully created.' }
        format.json { render :show, status: :created, location: @job_seeker }
      else
        format.html { render :new }
        format.json { render json: @job_seeker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_seekers/1
  # PATCH/PUT /job_seekers/1.json
  def update
    respond_to do |format|
      if @job_seeker.update(job_seeker_params)
        format.html { redirect_to @job_seeker, notice: 'Job seeker was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_seeker }
      else
        format.html { render :edit }
        format.json { render json: @job_seeker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_seekers/1
  # DELETE /job_seekers/1.json
  def destroy
    @job_seeker.delete
    respond_to do |format|
      format.html { redirect_to job_seekers_url, notice: 'Job seeker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_seeker
      @job_seeker = JobSeeker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_seeker_params
      params.require(:job_seeker).permit(:name_first, :name_last, :email, :password, :phone_number, :skills, :resume)
    end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/employer_helper.rb
module EmployerHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/job_seeker_helper.rb
module JobSeekerHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/login_helper.rb
module LoginHelper
  def signed_in?
    #!current_login.nil?
    true
  end
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/job_seekers/_form.html.erb
<%= form_for(@job_seeker) do |f| %>
  <% if @job_seeker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_seeker.errors.count, "error") %> prohibited this job_seeker from being saved:</h2>

      <ul>
      <% @job_seeker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_first %><br>
    <%= f.text_field :name_first %>
  </div>
  <div class="field">
    <%= f.label :name_last %><br>
    <%= f.text_field :name_last %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :skills %><br>
    <%= f.text_field :skills %>
  </div>
  <div class="field">
    <%= f.label :resume %><br>
    <%= f.text_area :resume %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_seekers/edit.html.erb
<h1>Editing job_seeker</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_seeker %> |
<%= link_to 'Back', job_seekers_path %>

app/views/job_seekers/index.html.erb
<h1>Listing Job Applicants</h1>
<table class="pure-table pure-table-horizontal">


  <thead>
    <tr>
      <th>Name first</th>
      <th>Name last</th>
      <th>Email</th>
      <th>Password</th>
      <th>Phone number</th>
      <th>Skills</th>
      <th>Resume</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_seekers.each do |job_seeker| %>
      <tr>
        <td><%= job_seeker.name_first %></td>
        <td><%= job_seeker.name_last %></td>
        <td><%= job_seeker.email %></td>
        <td><%= job_seeker.password %></td>
        <td><%= job_seeker.phone_number %></td>
        <td><%= job_seeker.skills %></td>
        <td><%= job_seeker.resume %></td>
        <td><%= link_to 'Show', job_seeker %></td>
        <td><%= link_to 'Edit', edit_job_seeker_path(job_seeker) %></td>
        <td><%= button_to  'Destroy', job_seeker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job seeker', new_job_seeker_path %>

app/views/job_seekers/new.html.erb
<h1>New job_seeker</h1>

<%= render 'form' %>

<%= link_to 'Back', job_seekers_path %>

app/views/job_seekers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name first:</strong>
  <%= @job_seeker.name_first %>
</p>

<p>
  <strong>Name last:</strong>
  <%= @job_seeker.name_last %>
</p>

<p>
  <strong>Email:</strong>
  <%= @job_seeker.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @job_seeker.password %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @job_seeker.phone_number %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @job_seeker.skills %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @job_seeker.resume %>
</p>

<%= link_to 'Edit', edit_job_seeker_path(@job_seeker) %> |
<%= link_to 'Back', job_seekers_path %>