config/routes.rb
Rails.application.routes.draw do

  resources :categories

  resources :jobs

  resources :job_applications

  root :to => 'demo#landing'

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, :has_one => :job_seeker
  resources :admin_users

  resources :login

  resources :user

  resources :jobs

  resources :demo

  get "error"=>"demo#error",:as => "error"
  get "contact"=>"demo#contact", :as => "contact"
  resources :employers

  resources :job_seeker
  post "/status" =>  "job_applications#status"

  resources :job_applications
  get "applicationsbyjobid" => "jobapplications#applicationsbyjobid", :as =>"applicationsbyjobid"

  get "edit_status" =>"jobapplications#editstatus", :as =>"edit_applicationstatus"
  get "create_job" =>"jobs#new", :as =>"create_job"

match ':controller(/:action(/:id))', :via => [:get,:post]

end

app/models/job.rb
class Job < ActiveRecord::Base

  belongs_to :employer
  belongs_to :category

  has_many :job_applications
  has_many :tags, :class_name => 'Job'
  accepts_nested_attributes_for :tags, :allow_destroy => true
  attr_accessible :title,:description,:application_deadline, :category_id, :employer
  def self.search(search)
    if search
      # paginate :per_page => 5, :page => 1,
      # :conditions => ["title LIKE '%?' ",search,search], :order => 'title'
      find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
    else
      all
    end
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController


  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
    @recommended_job_ids = Array.new
    if current_user.role == 1
      @jobs_applications = JobApplication.where(job_seeker_id: JobSeeker.find_by_user_id(current_user.id.to_s))
      @jobs_applied_ids = Array.new
      @jobs_applications.each { |ja| @jobs_applied_ids<< ja.job_id }
      @jobs_applied_ids.each do |job|
        @job_tag = JobTag.where(job_id: job)

        puts @job_tag

        @jobtag = JobTag.where(tag_id: @job_tag.each { |j| j.tag_id })

        @jobtag.each do |jt|
          @recommended_job_ids << jt.job_id
        end
      end
      @recommended_job_ids = @recommended_job_ids.uniq
    end

    @recommended_jobs=Job.where(id: @recommended_job_ids)
    puts '________________________________________________'
    puts @recommended_jobs

  end



  def jobsbyemployer
    @jobs = Job.where("employers_id = ?", Employer.find_by_user_id(current_user_id))
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    q = "%#{params[:search]}%"
    @jobs = Job.where("lower(title) like ? or lower(description) like ? ", q.downcase, q.downcase)
    render "index"
  end

  def new
    @categories = Category.all
    puts @categories
    @job = Job.new
    @tag = Tag.new

  end

  def edit
  end


  def create
    @job = Job.new(job_params)
    @result = params["tag_value"].split(" ")
    respond_to do |format|

      @job.employers_id = Employer.find_by_user_id(current_user.id).id

      @job.save
      var_job_id = @job.id
      if var_job_id
        @result.each { |x|
          tag = Tag.find_by_tag_value(x)
          if tag
            tag_id =tag.id
          else
            tag = Tag.new(:tag_value => x)
            tag.save
            tag_id = tag.id
          end
          job_tags =  JobTag.new
          job_tags.tag_id =  tag_id
          job_tags.job_id =  var_job_id
          job_tags.save
        }
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @job.delete
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end


    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :application_deadline, :category_id, :tags_id, :employers_id)
    end
end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :application_deadline %><br>
    <%= f.datetime_select :application_deadline %>
  </div>

    <div class="form-group">
      <label for="JobCategory" class="col-sm-3 control-label">Category</label>
      <div class="col-sm-6">
        <select id="job_category_id" name="job[category_id]" class="form-control" required>
          <% if !@categories.nil? %>
              <% @categories.each do |category| %>
                  <option value="<%= category.id %>" <%= 'selected' if category == @job.category %>><%= category.name %></option>
              <% end %>
          <% end %>
        </select>
      </div>
    </div>
    <td>
      <div><label for="tag_value">Tags</label><br />
        <input id="tag_value" name="tag_value" type="text" />
      </div>
    </td>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/_form_applicants.html.erb
<h1>Listing Applicants</h1>
<table>
  <thead>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>User ID</th>
    <th>Phone Number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @job_seekers.each do |jobseeker| %>
      <tr>
        <td><%= jobseeker.first_name %></td>
        <td><%= jobseeker.last_name %></td>
        <td><%= jobseeker.user_id %></td>
        <td><%= jobseeker.phone_number %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/jobs/delete.html.erb
<h1>Jobs#delete</h1>
<p>Find me in app/views/jobs/delete.html.erb</p>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
    <table class="pure-table pure-table-bordered">
      <% if current_user.role == 2 %>
          <h1>Jobs Created by you</h1>
          <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Application deadline</th>
    <th>Category</th>
    <th>Tags</th>
    <th>Employers</th>
  </tr>
  </thead>

  <tbody>
  <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.description %></td>
        <td><%= job.application_deadline %></td>
        <td>
          <% @category =  Category.find_by_id(job.category_id) %>
          <%= @category.name%>
        </td>
        <td>
          <%
          @job_tag = JobTag.where(job_id: job.id)

          puts @job_tag
          puts "hello"
             @tag = Array.new
          @job_tag.each { |j| @tag << j.tag_id }
          puts  @tag

          %>
           <%@tag.each  do |s| %>
              <%= Tag.find_by_id(s).tag_value%>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= button_to 'Destroy', job, method: :delete, data: { confirm: 'Are you Sure?' } %></td>
      </tr>
  <% end %>
  </tbody>


<br>

<%= link_to 'New Job', new_job_path %>
<%else %>
    <h1>Listing jobs</h1>
      <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Application deadline</th>
        <th>Category</th>
        <th>Tags</th>
        <th>Employers</th>
      </tr>
      </thead>

      <tbody>
      <% @jobs.each do |job| %>
          <tr>
            <td><%= job.title %></td>
            <td><%= job.description %></td>
            <td><%= job.application_deadline %></td>
            <td><%= job.category_id %></td>
            <td><%= job.employers_id %></td>
            <td><%= link_to 'Apply', new_job_application_path(job) %></td>
          </tr>
      <% end %>
      </tbody>
      <%end%>
    </table>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Application deadline:</strong>
  <%= @job.application_deadline %>
</p>

<p>
  <strong>Category:</strong>
  <%= @job.category_id %>
</p>



<p>
  <strong>Employers:</strong>
  <%= @job.employers_id %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>