config/routes.rb
Rails.application.routes.draw do

  resources :categories

  resources :jobs

  resources :job_applications

  root :to => 'demo#landing'

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, :has_one => :job_seeker
  resources :admin_users

  resources :login

  resources :user

  resources :jobs

  resources :demo

  get "error"=>"demo#error",:as => "error"
  get "contact"=>"demo#contact", :as => "contact"
  resources :employers

  resources :job_seeker
  post "/status" =>  "job_applications#status"

  resources :job_applications
  get "applicationsbyjobid" => "jobapplications#applicationsbyjobid", :as =>"applicationsbyjobid"

  get "edit_status" =>"jobapplications#editstatus", :as =>"edit_applicationstatus"
  get "create_job" =>"jobs#new", :as =>"create_job"

match ':controller(/:action(/:id))', :via => [:get,:post]

end

app/models/job_application.rb
class JobApplication < ActiveRecord::Base

  belongs_to :jobs
  belongs_to :job_seekers
  validates :job_id,  presence: true
  validates :job_seeker_id, presence: true
  validates :status, :presence => true

  attr_accessible :cover_letter,:application_deadline

# <!-- Assigning Integer Values to various Job Application states - Using the standard Naming convention for Constants -->
  STATE_PENDING = 0
  STATE_FUTUREINTERVIEW = 1
  STATE_NOTAFIT = 2

  STATE_PENDING_STRING = 'Pending'
  STATE_FUTUREINTERVIEW_STRING = 'Future interview'
  STATE_NOTAFIT_STRING = 'Not a fit'

  def getApplicationState
    case self.status
      when STATE_FUTUREINTERVIEW
        return STATE_FUTUREINTERVIEW_STRING
      when STATE_PENDING
        return STATE_PENDING_STRING
      when STATE_NOTAFIT
        return STATE_NOTAFIT_STRING
      else
        return 'Pending review'
    end
  end

end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :set_job_application, only: [:show, :edit, :update, :destroy]

  # GET /job_applications
  # GET /job_applications.json
  def index
    @job_applications = JobApplication.all
  end



  def applicationsbyjobid
    @list = Jobapplication.where("job_id = ?",params[:id])
  end

  # GET /job_applications/1
  # GET /job_applications/1.json
  def show
    if current_user.role == 2
      @jobs = Job.find_by_employers_id(Employer.find_by_user_id(current_user.id).id)
    elsif current_user.role == 1
      JobApplication.find_by_job_seeker_id(current_user.id)
      end
  end

  # GET /job_applications/new
  def new
    @job_application = JobApplication.new
    flash[:job_id] = params["format"]
  end

  # GET /job_applications/1/edit
  def edit
  end


  def editstatus
    @list = Jobapplication.find(params[:id])
  end

  # POST /job_applications
  # POST /job_applications.json
  def create
    @job_application = JobApplication.new(job_application_params)
    @job_application.status = "pending review"
    @job_application.job_seeker_id = current_user.id
    @job = Job.find_by_id(@job_id)
    @job_application.job_id = flash[:job_id].to_i
    @job_application.application_deadline = Job.find_by_id(flash[:job_id].to_i).application_deadline
    respond_to do |format|
      if @job_application.save
        format.html { redirect_to @job_application, notice: 'Job application was successfully created.' }
        format.json { render :show, status: :created, location: @job_application }
      else
        format.html { render :new }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_applications/1
  # PATCH/PUT /job_applications/1.json
  def update
    respond_to do |format|
      if @job_application.update(job_application_params)
        format.html { redirect_to @job_application, notice: 'Job application was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_application }
      else
        format.html { render :edit }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  def status
    job_application = JobApplication.find_by_id(params["id"])
    status = params["status"]
    puts status
    case status
      when 1.to_s
        status="Pending review"
      when 2.to_s
        status="Not a Fit"
      when 3.to_s
        status="Future Interview"
      else
        status="Pending review"


    end
    job_application.update_attribute("status",status)

    @job_applications = JobApplication.all
    render "index", notice: 'Job application was successfully updated.'
    end

  # DELETE /job_applications/1
  # DELETE /job_applications/1.json
  def destroy
    @job_application.delete
    respond_to do |format|
      format.html { redirect_to job_applications_url, notice: 'Job application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_application
      @job_application = JobApplication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_application_params
      params.require(:job_application).permit( :cover_letter, :application_deadline)
    end
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
end

app/views/job_applications/_form.html.erb
<%= form_for(@job_application) do |f| %>
  <% if @job_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_application.errors.count, "error") %> prohibited this job_application from being saved:</h2>

      <ul>
      <% @job_application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>


        <% end %>
  <div class="field">
    <%= f.label :cover_letter %><br>
    <%= f.text_area :cover_letter %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_applications/applicationsbyjobid.html.erb
<div class="" align="center">
    <h1>Job Applications</h1>

    <table id="applicationsbyjobid" class="pure-table pure-table-horizontal">
      <thead>
      <tr>
        <th>Cover</th>
        <th>Date</th>
        <th>Status</th>
        <th>Applicant</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @list.each do |jobapplication| %>
          <tr>
            <td><%= jobapplication.coverletter %></td>
            <td><%= jobapplication.dateofapplication %></td>
            <td><%= jobapplication.status %></td>
            <td><%= link_to jobapplication.jobseeker.name,{controller: "jobseekers" , action: "view" , :id => jobapplication.jobseeker.id, :jobid => jobapplication.job.id}%></td>
            <td><%= link_to 'Change Status', {controller: "jobapplications" , action: "editstatus" , :id => jobapplication.id }%></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Back', my_jobs_path %>

app/views/job_applications/edit.html.erb
<h1>Editing job_application</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_application %> |
<%= link_to 'Back', job_applications_path %>

app/views/job_applications/index.html.erb
<h1>Listing Job Applications</h1>

<table class="pure-table pure-table-horizontal">
  <thead>
    <tr>
      <th>Job</th>
      <th>Applicant</th>
      <th>Status</th>
      <th>Cover letter</th>
      <th>Application deadline</th>
  
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @job_applications.each do |job_application| %>
      <tr>
        <td><%= Job.find_by_id(job_application.job_id).title %></td>
        <td><%jobseeker =  JobSeeker.find_by_user_id(job_application.job_seeker_id.to_s)
if jobseeker != nil %>
<%= jobseeker.first_name%>
<%else %>
abc
<%end%></td>
        <td><%= job_application.getApplicationState %></td>
        <td><%= job_application.cover_letter %></td>
        <td><%= job_application.application_deadline %></td>
        <% if current_user.role == 1 %>
        <td><%= link_to 'Show', job_application %></td>
        <td><%= link_to 'Edit', edit_job_application_path(job_application) %></td>

        <td><%= link_to 'Destroy', job_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <%elsif current_user.role == 2%>
            <%= form_for job_application,:url => status_path(job_application),method: :post do |f| %>
                <%= hidden_field_tag :id, job_application.id %>
            <td>
              <div class="col-sm-3">
                <% index = job_application.status %>
                <select type="number" id="status" name="status" class="form-control">
                  <option value="1" <%= 'selected' if index == "Pending review" %>>Pending</option>
                  <option value="2" <%= 'selected' if index == "Not a Fit" %>>Not a Fit</option>
                  <option value="3" <%= 'selected' if index == "Future Interview" %>>Future Interview</option>
                </select>
              </div>
            </td>
            <td>
            <div class="form-group ">

                  <div class="actions">
                    <%= f.submit %>
                  </div>
                  <% end%>

            </div>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.role == 1 %>
<%= link_to 'New Job application', new_job_application_path %>
<%end%>

app/views/job_applications/new.html.erb
<h1>New job_application</h1>

<%= render 'form' %>

<%= link_to 'Back', job_applications_path %>

app/views/job_applications/show.html.erb
    <p id="notice"><%= notice %></p>

<p>
  <strong>Job:</strong>
  <%= @job_application.job_id %>
</p>

<p>
  <strong>Job seeker:</strong>
  <%= @job_application.job_seeker_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @job_application.status %>
</p>

<p>
  <strong>Cover letter:</strong>
  <%= @job_application.cover_letter %>
</p>

<p>
  <strong>Application deadline:</strong>
  <%= @job_application.application_deadline %>
</p>

<%= link_to 'Edit', edit_job_application_path(@job_application) %> |
<%= link_to 'Back', job_applications_path %>