config/routes.rb
Rails.application.routes.draw do

  resources :categories

  resources :jobs

  resources :job_applications

  root :to => 'demo#landing'

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, :has_one => :job_seeker
  resources :admin_users

  resources :login

  resources :user

  resources :jobs

  resources :demo

  get "error"=>"demo#error",:as => "error"
  get "contact"=>"demo#contact", :as => "contact"
  resources :employers

  resources :job_seeker
  post "/status" =>  "job_applications#status"

  resources :job_applications
  get "applicationsbyjobid" => "jobapplications#applicationsbyjobid", :as =>"applicationsbyjobid"

  get "edit_status" =>"jobapplications#editstatus", :as =>"edit_applicationstatus"
  get "create_job" =>"jobs#new", :as =>"create_job"

match ':controller(/:action(/:id))', :via => [:get,:post]

end

app/models/employer.rb
class Employer < ActiveRecord::Base
	belongs_to :admin, :class_name =>"AdminUser", :foreign_key => "admin_user_id"
	has_many :tags
	has_many :jobs

  attr_accessible :company_name

  validates :admin_id, :presence => true
 
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
before_action :set_employer, only: [:show, :edit, :update, :destroy]


  def index
    @employers = Employer.all
  end

  def show
  end

  def new
    @employer = Employer.new
  end

  def edit
  end


  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      @employer.admin_id = current_user.id
      if User.find_by_email(params["email"])
        @employer.errors.add(:email, "Already in use")
        format.html { render action: 'new' }
        format.json { render json: @employer.errors }

      else
      user = User.new
      #user.password = User.new(password: @admin_user.password).encrypted_password
      user.password = params["password"]
      user.email = params["email"]
      user.role = 2
      user.save
      @employer.user_id = user.id
      if @employer.save

        format.html { redirect_to @employer, notice: 'Employer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @employer }
      else
        format.html { render action: 'new' }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
    end
    end

  def update
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to @employer, notice: 'Employer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @employer.delete
    respond_to do |format|
      format.html { redirect_to employers_url }
      format.json { head :no_content }
    end
  end

  private
    def set_employer
      @employer = Employer.find(params[:id])
    end

    def employer_params
      params.require(:employer).permit(:company_name)
    end
end
  

app/helpers/employer_helper.rb
module EmployerHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_form.html.erb
<%= form_for(@employer) do |f| %>
  <% if @employer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
      <% @employer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :company_name %><br>
      <%= f.text_field :company_name %>
    </div>

    <div><label for="user_email">Email</label><br />
      <input id="email" name="email" type="text" /></div>
    <div><label for="user_password">Password</label><br />
      <input id="password" name="password" type="password" /></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employers/edit.html.erb
<h1>Editing employer</h1>

<%= render 'form' %>

<%= link_to 'Show', @employer %> |
<%= link_to 'Back', employers_path %>

app/views/employers/index.html.erb
<h1>Listing employers</h1>

  <table class="pure-table pure-table-bordered">
        <thead>
        <tr>
          <th>Company Name</th>
          <th>Admin ID</th>
        </tr>
        </thead>

  <tbody>
    <% @employers.each do |employer| %>
      <tr>
        <td><%= employer.company_name %></td>
        <td><%= employer.admin_id %></td>
        <td><%= link_to 'Show', employer %></td>
        <td><%= link_to 'Edit', edit_employer_path(employer) %></td>
        <td><%= button_to 'Destroy', employer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Employer', new_employer_path %>

app/views/employers/new.html.erb
<h1>New employer</h1>

<%= render 'form' %>

<%= link_to 'Back', employers_path %>

app/views/employers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employer.company_name %>
   <strong>User ID</strong>
  <%= @employer.admin_id %>

</p>
<%= link_to 'Edit', edit_employer_path(@employer) %> |
<%= link_to 'Back', employers_path %>